color0 #57423a
color1 #ffb4ab
color2 #ffb598
color3 #fdb699
color4 #d6c861
color5 #ffb598
color6 #fdb699
color7 #f3ded7
color8 #a58b81
color9 #ffb4ab
color10 #ffb598
color11 #fdb699
color12 #d6c861
color13 #ffb598
color14 #fdb699
color15 #f3ded7

cursor                #f3ded7
cursor_text_color     #1b110d
background            #1b110d
foreground            #f3ded7
selection_foreground  #dec0b5
selection_background  #57423a
active_border_color   #ffb598
inactive_border_color #57423a
url_color             #ffb598

active_tab_foreground   #591d00
active_tab_background   #ffb598
inactive_tab_foreground #dec0b5
inactive_tab_background #57423a
cursor_trail_color      #dec0b5
