bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        10.0
font_family      family="JetBrainsMono Nerd Font"

disable_ligatures no
enable_audio_bell no

shell               zsh
shell_integration   disabled

background_opacity              1
scrollbar_handle_opacity        0
scrollbar_track_opacity         0
scrollbar_track_hover_opacity   0
confirm_os_window_close         0

cursor_shape block
cursor_trail 1

url_style curly

window_padding_width  8
window_margin_width   8




include themes/noctalia.conf
